### ISSUE TITLE
Check HISTORY for long strings

### ISSUE THREAD

**Issue by mtceballos** [bcobo/SIRENA#11]
Library parameters gets always cut in the second line in files header

**Comment by bcobo** [comment]
Se usa la función de heasoft 'HDpar_stamp' para escribir todos los parámetros de entrada en tesreconstruction.c en un bloque HISTORY en la extensión Primary del fichero de salida. 
Cuando esos parámetros son muy largos (por el path por ejemplo) deja de escribir algunos caracteres entre la segunda y la tercera línea del parámetro. 
He mandado un mensaje a FTOOLS Help Desk (FTOOLS #3363]).

**Comment by bcobo** [comment]
La respuesta de FTOOLS Help Desk ha sido mandarnos una versión corregida de `headas_parstamp.c` que debería solucionar el problema. Nos dan las siguientes instrucciones:

_To update your installation, please copy `headas_parstamp.c` into heacore/heautils/ and then
$ cd heacore/heautils
$ hmake
$ hmake install_

**Comment by bcobo** [comment]
Hemos estado intentando que nos funcionara la corrección que nos habían enviado de FTOOLS Help Desk. El problema es que en el entorno SIXTE no se actualizaba el fichero aunque lo copiásemos a mano en la ruta adecuada. Hemos escrito a sixte-dev@fau.de y ellos actualizaron headas_parstamp.c en el simput master.

Branches: update_headas_parstamp to master
Author: Maximilian Lorenz
Assignee: Maximilian Lorenz
    Fixes an error while writing very long input parameters with HDpar_stamp
Merge Request !48 was merged
