### ISSUE TITLE
Implement Rise time calculation

### ISSUE THREAD

**Issue by mtceballos** [bcobo/SIRENA#13]
See document about processing baseline

**Comment by mtceballos** [comment]
Comment al documento de Onboard processing:
5. Plot in Sec 6.3: why is the “rise time” defined using only the
     cluster of 3 points nearest the 50% point? I’d think it would be
     less noisy to draw the line between the 0 and 50%ile points, or
     perhaps the 10 and 50 %iles? The method shown here extrapolates a
     line a long way based on 3 closely spaced, noisy points.

**Comment by bcobo** [comment]
According to the previous comment of a referee about the "Onboard processing" document, the calculus of the rise/fall times follow at the moment (SIRENA version v.3.5.0) the next steps ('obtainRiseFallTimes' in 'tasksSIRENA.cpp'):

RISE TIME 
- Find the maximum of each pulse: amax
- Baseline of each pulse: abase
- Find the first sample in the rising part above the 10% and 50%: t10 and t50
- Line by using 2 points: (t10,a10) and (t50,a50)
- t0 calculated with the previous line equation (t0,abase)
- tmax calculated with the previous line equation (tmax,amax)
- Rise time = tmax-t0
FALL TIME
- Find the first sample in the decreasing part below the 50% and 10%: t50 and t10
- Line by using 2 points: (t50,a50) and (t10,a10)
- t0 with the previous line equation(t0,abase)
- tmax with the previous line equation(tmax,amax)
- Fall time = t0-tmax
