### ISSUE TITLE
Re-define I2RFITTED transformation

### ISSUE THREAD

**Issue by mtceballos** [bcobo/SIRENA#16]
Calculate pseudo-resistance as R/V0 (multiplicative factors do not have an effect)

Use Ifit as IBIAS (or I0_START) instead of hard-coded value

**Comment by bcobo** [comment]
If ADU_CNV keyword in the input FITS file:

   R/V0 = -1/(Ifit+ADC) being Ifit=ADU_BIAS

If ADU_CNV keyword NOT in the input FITS file:

      aducnv = (IMAX-IMIN)/65534 calculated by using the IMIN and IMAX keywords in the events file
      Quantification levels = 65534
      R/V0 = -1/(Ifit+ADC) being Ifit=I0_START(adu)=I0_START(A)/aducnv(A/adu)

**Comment by bcobo** [comment]
R/V0 = -1/(Ifit+ADC) but Ifit is not ADU_BIAS. Changing from adu into A is not by using ADU_CNV factor but using the expression
 I(A) = I_BIAS(A) + ADU_CNV(A/adu)*[I(adu)-ADU_BIAS(adu)]
