### ISSUE TITLE
Adapt SIRENA to new TesRecord format in xifusim

### ISSUE THREAD

**Issue by mtceballos** [bcobo/SIRENA#20]
Updated TesRecord format in xifusim:
-  For performance reasons, xifusim now avoids writing any variable width columns
- TesRecords now use a fixed-length ADC column, with a width equal to the default record length. If a record is extended due to pileup, the additional data is written into the next FITS row(s). The number of samples that still need to be read are indicated by the EXTEND keyword
- The number of records in a TESRECORD extension can still be counted by counting the nr. of rows with an EXTEND value of 0
- The PH_ID column is also restricted to a fixed length column of length 3

**Comment by bcobo** [comment]
A dedicated branch called "varRecordLength" (VARiable Record Length).
Merged with the master on Mar 10, 2021 (SIRENA version 3.8.7).

**Comment by mtceballos** [comment]
Closed
