### ISSUE TITLE
Reconstruction with EnergyMethod INTCOVAR looks for Noise file

### ISSUE THREAD

**Issue by mtceballos** [bcobo/SIRENA#36]
Where/how/why to provide noise file?

TESRECONS 11.0.1

Command: 

`tesrecons Recordfile=../input/xifusim_pairs_3keV_6keV_sep3500samples.fits TesEventFile=events_pairs_3keV_6keV_sep3500samples_covar_reference.fits LibraryFile=library_all_reference.fits XMLFile=../input/1pix_lpa2.5a_fll_SIRENAintegration.xml preBuffer=yes clobber=yes EnergyMethod=INTCOVAR OFStrategy=BYGRADE LagsOrNot=0 OFLib=no`

Output:

```
Running TESRECONS v11.0.1
Read file ../input/1pix_lpa2.5a_fll_SIRENAintegration.xml
Number of pixels after removing overlaps: 0
 
Attention: preBuffer used => Parameters of library filters read from XML file
Error in loadNoise: The necessary noise file does not exist

```

Files location: `/dataj6/sw/remove_sirena/SIRENA/test/sirena_tests/data/reference`

**Comment by bcobo** [comment]
First of all, sure you tried to run the _tesrecons_ command with **EnergyMethod=INTCOVAR**  and **OFLib=yes**. Then, there was an error message saying "EnergyMethod=INTCOVAR => OFLib should be 'no' ". And clearly, when **OFLib=no**, it is necessary a valid noise file (if not, "Error in loadNoise: The necessary noise file does not exist" appeared).

In [b8b3546](https://github.com/bcobo/SIRENA/commit/b8b3546040dd43c6469b188e7270b6dec50c903f) if _EnergyMethod=INTCOVAR_, _OFLib_ should be _yes_ (and the noise file is not necessary).
