### ISSUE TITLE
Optimal filters in library do not have prebuffer although the XML specifies a prebuffer

### ISSUE THREAD

**Issue by mtceballos** [bcobo/SIRENA#38]
See library: 

`/dataj6/ceballos/INSTRUMEN/EURECA/realData/GSFC/10Jan2020_RTS/channel_1/library_Kas_4000_pB1000_filt_thS3.5.fits`

created with XML:

`/dataj6/ceballos/INSTRUMEN/EURECA/realData/GSFC/GSFC_maxfl4000_pB1000.xml`

Command line used is in header of library file

**Comment by mtceballos** [comment]
parameter `filtlen` was misspelled in .xml file

It should raise an error in this case though. I leave this issue open until this is done.

**Comment by bcobo** [comment]
libsixte/advdet.c (from SIXTE) has to me modified to check if PRE, POST, PB or PRE, POST, FILTLEN are misspelled in the XML file: 

_if (xmlparsedata->det->nrecons == 1)    //SIRENA
		{
			if (xmlparsedata->det->inpixel){
				xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades=realloc(xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades,
																					 (xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades+1)*sizeof(*(xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades)));
				if (xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades==NULL){
					xmlparsedata->status=EXIT_FAILURE;
					SIXT_ERROR("Realloc of grading array failed.");
					return;
				}
				xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades[xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades].value=getXMLAttributeInt(attr, "NUM");
				xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades[xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades].gradelim_pre=getXMLAttributeLong(attr, "PRE");
				if (getXMLAttributeLong(attr, "FILTLEN") == 0) // XML: pre post pB
				{
					**if ((getXMLAttributeLong(attr, "POST") == 0) || (getXMLAttributeLong(attr, "PB") == 0) || (getXMLAttributeLong(attr, "PRE") == 0))
					{
						xmlparsedata->status=EXIT_FAILURE;
						SIXT_ERROR("XML syntax error (GRADING node): PRE, POST, PB?");
						return;
					}**
					xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades[xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades].gradelim_post=getXMLAttributeLong(attr, "POST");
					xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades[xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades].grade_preBuffer=getXMLAttributeLong(attr, "PB");
				}
				else // XML: pre post filtlen
				{
					**if ((getXMLAttributeLong(attr, "FILTLEN") == 0) || (getXMLAttributeLong(attr, "POST") == 0) || (getXMLAttributeLong(attr, "PRE") == 0))
					{
						xmlparsedata->status=EXIT_FAILURE;
						SIXT_ERROR("XML syntax error (GRADING node): PRE, POST, FILTLEN?");
						return;
					}**
					xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades[xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades].gradelim_post=getXMLAttributeLong(attr, "FILTLEN");
					xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades[xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades].grade_preBuffer=getXMLAttributeLong(attr, "FILTLEN")-getXMLAttributeLong(attr, "POST");
				}

				xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades++;
			} else {
				for (int i=0;i<xmlparsedata->det->nrecons;i++){
					xmlparsedata->det->recons[i].grades=realloc(xmlparsedata->det->recons[i].grades,
																(xmlparsedata->det->recons[i].ngrades+1)*sizeof(*(xmlparsedata->det->recons[i].grades)));
					if (xmlparsedata->det->recons[i].grades==NULL){
						xmlparsedata->status=EXIT_FAILURE;
						SIXT_ERROR("Realloc of grading array failed.");
						return;
					}
					xmlparsedata->det->recons[i].grades[xmlparsedata->det->recons[i].ngrades].value=getXMLAttributeInt(attr, "NUM");
					xmlparsedata->det->recons[i].grades[xmlparsedata->det->recons[i].ngrades].gradelim_pre=getXMLAttributeLong(attr, "PRE");

					if (getXMLAttributeLong(attr, "FILTLEN") == 0) // XML: pre post pB
					{
						if ((getXMLAttributeLong(attr, "POST") == 0) || (getXMLAttributeLong(attr, "PB") == 0) || (getXMLAttributeLong(attr, "PRE") == 0))
						{
							xmlparsedata->status=EXIT_FAILURE;
							SIXT_ERROR("XML syntax error (GRADING node): PRE, POST, PB?");
							return;
						}
						xmlparsedata->det->recons[i].grades[xmlparsedata->det->recons[i].ngrades].gradelim_post=getXMLAttributeLong(attr, "POST");
						xmlparsedata->det->recons[i].grades[xmlparsedata->det->recons[i].ngrades].grade_preBuffer=getXMLAttributeLong(attr, "PB");
					}
					else // XML: pre post filtlen
					{
						if ((getXMLAttributeLong(attr, "FILTLEN") == 0) || (getXMLAttributeLong(attr, "POST") == 0) || (getXMLAttributeLong(attr, "PRE") == 0))
						{
							xmlparsedata->status=EXIT_FAILURE;
							SIXT_ERROR("XML syntax error (GRADING node): PRE, POST, FILTLEN?");
							return;
						}
						xmlparsedata->det->recons[i].grades[xmlparsedata->det->recons[i].ngrades].gradelim_post=getXMLAttributeLong(attr, "FILTLEN");
						xmlparsedata->det->recons[i].grades[xmlparsedata->det->recons[i].ngrades].grade_preBuffer=getXMLAttributeLong(attr, "FILTLEN")-getXMLAttributeLong(attr, "POST");
					}
					xmlparsedata->det->recons[i].grades[xmlparsedata->det->recons[i].ngrades].rmf=NULL;

					xmlparsedata->det->recons[i].ngrades++;
				}
			}
        }_

**Comment by bcobo** [comment]
A SIXTE file (libsixte/advdet.c) would have to be modified.
