### ISSUE TITLE
question: prebuffers of optimal filters

### ISSUE THREAD

**Issue by mtceballos** [bcobo/SIRENA#39]
How does `terecons` know which prebuffer corresponds to a given optimal filter?

Is it read from the xml?
I've run `tesrecons` (new) for 0-pad with a library created with a previous version of `tesreconstruction` and therefore with an XML using an old format (post & pB instead of post & filtlen). How did it do the pB calculation?

**Comment by bcobo** [comment]
En SIXTE/libsixte/advdet.c se contempla que pueda ser un fichero XML de los nuevos (pre,post,filtlen) o de los viejos (pre,post,pB).

 _if (getXMLAttributeLong(attr, "FILTLEN") == 0) // XML: pre post pB
				{
					xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades[xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades].gradelim_post=getXMLAttributeLong(attr, "POST");
					xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades[xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades].grade_preBuffer=getXMLAttributeLong(attr, "PB");
				}
				else // XML: pre post filtlen
				{
					xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades[xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades].gradelim_post=getXMLAttributeLong(attr, "FILTLEN");
					xmlparsedata->det->recons[xmlparsedata->det->nrecons].grades[xmlparsedata->det->recons[xmlparsedata->det->nrecons].ngrades].grade_preBuffer=getXMLAttributeLong(attr, "FILTLEN")-getXMLAttributeLong(attr, "POST");
				}_

**Comment by mtceballos** [comment]
Thanks!
