### ISSUE TITLE
Check different baseline values and how it affects 0-padding

### ISSUE THREAD

**Issue by mtceballos** [bcobo/SIRENA#8]
- Subtract 1700 to xifusim/gainScale (5000 pulses): sep40000sam_5000p_1keV_jitter_bbfb.fits
- Subtract 1700 to xifusim/ (2000 pulses): sep40000sam_2000p_1keV_jitter_bbfb.fits
BBFB, 0.2-8 keV, samprate

**Comment by bcobo** [comment]
Los ficheros para la gainScale (5000p) están en dos carpetas base100 ó base3000 dependiendo de si hemos restado 1700 adus para obtener una baseline de ~100 adus o hemos sumado 1200 para tener una baseline de ~3000 adus:  

/dataj6/ceballos/INSTRUMEN/EURECA/ERESOL/PAIRS/xifusimLPA75um/gainScale/base100
/dataj6/ceballos/INSTRUMEN/EURECA/ERESOL/PAIRS/xifusimLPA75um/gainScale/base3000

y no cambian el nombre, sep40000sam_5000p_*keV_jitter_bbfb.fits

Igual para los ficheros de test (2000p). Están en las carpetas:

/dataj6/ceballos/INSTRUMEN/EURECA/ERESOL/PAIRS/xifusimLPA75um/base100
/dataj6/ceballos/INSTRUMEN/EURECA/ERESOL/PAIRS/xifusimLPA75um/base3000

y se llaman sep40000sam_2000p_*keV_jitter_bbfb.fits

En el proceso de cambiar la baseline en los ficheros (subtractBaseline_100_5000p.py, addBaseline_3000_5000p.py, subtractBaseline_100.py, addBaseline_3000.py) hemos visto que para las energías de 0.2 y 0.5 eV los ficheros son nuevos (8 extensiones) pero para las energías de 1 a 8 keV incluidas los ficheros son viejos (y sólo tienen 1 extension).
