### ISSUE TITLE
jitter/parabola

### ISSUE THREAD

**Issue by mtceballos** [bcobo/SIRENA#9]
1)  No jitter, no lags @ 6 keV, 8192 (2000 pulsos)
2) Jitter, parabola, 2D calibration, 8192

If 2) is better than 1) => parabola is required

**Comment by bcobo** [comment]
El fichero es  sep40000sam_2000p_6keV_**nojitter**_bbfb.fits y está en la carpeta /dataj6/ceballos/INSTRUMEN/EURECA/ERESOL/PAIRS/xifusimLPA75um

**Comment by mtceballos** [comment]
1) FWHM=1.70eV
2) FWHM=2.29eV
Both reconstructed with same (jitter)(noisy) library. Same xifusim than that used for methods comparison.
Parabola seems to be a proxy for jitter correction (does some correction but not definitive)

**Comment by mtceballos** [comment]
Gain scale for nojitter must be created to correct FWHM (for uncalibrated files it is always ~1.69eV)

**Comment by mtceballos** [comment]
Outdated
